### PR TITLE
add file type

### PR DESCRIPTION
**Pull request by sonots**
This is my first commit to configspec. Could you review this?

I added `file` type to enable

``` ruby
describe file('filename') do
  it { should contain 'contents' }
end
```

which appends `contents` to `filename` file. 

I very wondered the specification of configspec, but tried to match with serverspec http://serverspec.org/resource_types.html#file. What do you think of this?

This pull request requires https://github.com/serverspec/specinfra/pull/32, which adds `append` command. Without a release of specinfra, the test of configspec will fail.

### CODE REVIEW

**Comment by sonots** [comment]
@travis Yes, test fails without a release of specinfra.

**Comment by mizzy** [comment]
I don't like to add a function appending lines to file.

Configspec is a configuration management tool.I don't like such tools to have this kind of function.

I like these matchers for putting files.

``` ruby
describe file('filename') do
  it { should be_copied_from('path/to/filename') }
end
```

Or 

``` ruby
describe template('filename') do
  it { should be_sourced_from('path/to/filename.erb') }
end
```

But if you implement these functions, you should add functions to SpecInfra::Backend::Exec and SpecInfra::Backend::Ssh.

**Comment by mizzy** [comment]
Thanks!

**Comment by mizzy** [comment]
Released as v0.1.0.

**Pull request merged**
